# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=200, null=True)),
                ('answer_date', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostas',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'escolha',
                'verbose_name_plural': 'escolhas',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('1', 'One choice'), ('2', 'Multipla Escolha'), ('3', 'Texto')], max_length=1, verbose_name='Tipo')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='Data de publicação')),
                ('exp_date', models.DateTimeField(verbose_name='Data de expiração')),
                ('days', models.IntegerField(choices=[(1, '1 dia'), (7, '1 semana'), (30, '1 mês'), (365, '1 ano'), (3650, 'Indeterminado')], default=3650, verbose_name='Tempo para expirar')),
                ('question_status', models.CharField(choices=[('n', 'Não publicado'), ('p', 'Publicado')], default='p', max_length=1, verbose_name='Estado da questão')),
                ('answer_status', models.CharField(choices=[('n', 'Não publicado'), ('p', 'Publicado')], default='n', max_length=1, verbose_name='Estado da resposta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images', verbose_name='Imagem')),
                ('address', models.CharField(max_length=200)),
                ('permissao', models.IntegerField(default=0)),
                ('resultado', models.CharField(choices=[('n', 'Não publicado'), ('p', 'Publicado')], default='u', max_length=1)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'questão',
                'verbose_name_plural': 'questões',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('year_of_start', models.IntegerField(blank=True)),
                ('department', models.CharField(blank=True, max_length=40)),
                ('course', models.CharField(blank=True, max_length=40)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('academic_registry', models.IntegerField(default=0)),
                ('question_answer', models.ManyToManyField(related_name='question_answer', through='agora.Answer', to='agora.Question')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agora.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agora.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agora.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agora.User'),
        ),
    ]
