# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuespacoartigo',
            name='arquivo',
            field=models.FileField(blank=True, max_length=2000000, upload_to='C:\\virtual-agora\\media'),
        ),
    ]
