# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0002_auto_20160328_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='meuespacoartigo',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Endere\xc3\xa7o'),
        ),
        migrations.AlterField(
            model_name='initiallistquestion',
            name='questions',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name=b'Quest\xc3\xb5es'),
        ),
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[(b'1', b'Conhe\xc3\xa7a'), (b'2', b'Resultados'), (b'3', b'Comunidade'), (b'4', b'Participe')], max_length=1, verbose_name=b'Tipo'),
        ),
        migrations.AlterField(
            model_name='message',
            name='publ_date',
            field=models.DateTimeField(verbose_name=b'Data de publica\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='message',
            name='published',
            field=models.CharField(default=b'N\xc3\xa3o', max_length=3, verbose_name=b'Publicado?'),
        ),
        migrations.AlterField(
            model_name='meuespacoartigo',
            name='comentario',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Coment\xc3\xa1rio'),
        ),
        migrations.AlterField(
            model_name='meuespacoartigo',
            name='publ_date',
            field=models.DateTimeField(verbose_name=b'Data de publica\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='meuespacoartigo',
            name='secao',
            field=models.CharField(blank=True, max_length=30, verbose_name=b'Se\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='question',
            name='address',
            field=models.CharField(max_length=200, verbose_name=b'Endere\xc3\xa7o'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_status',
            field=models.CharField(choices=[(b'n', b'N\xc3\xa3o publicado'), (b'p', b'Publicado')], default=b'n', max_length=1, verbose_name=b'Estado da resposta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='days',
            field=models.IntegerField(choices=[(1, b'1 dia'), (7, b'1 semana'), (30, b'1 m\xc3\xaas'), (365, b'1 ano'), (3650, b'Indeterminado')], default=3650, verbose_name=b'Tempo para expirar'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(verbose_name=b'Data de expira\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='question',
            name='publ_date',
            field=models.DateTimeField(verbose_name=b'Data de publica\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_status',
            field=models.CharField(choices=[(b'n', b'N\xc3\xa3o publicado'), (b'p', b'Publicado')], default=b'p', max_length=1, verbose_name=b'Estado da quest\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name=b'T\xc3\xadtulo da Quest\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='question',
            name='resultado',
            field=models.CharField(choices=[(b'n', b'N\xc3\xa3o publicado'), (b'p', b'Publicado')], default=b'n', max_length=1),
        ),
        migrations.AlterField(
            model_name='termo',
            name='condition',
            field=models.CharField(default=b'N\xc3\xa3o', max_length=3, verbose_name=b'Condi\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='user',
            name='academic_registry',
            field=models.IntegerField(default=b'9999', verbose_name=b'Registro acad\xc3\xaamico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.CharField(blank=True, choices=[(b'1', b'Professor'), (b'2', b'Funcion\xc3\xa1rio'), (b'3', b'Aluno'), (b'4', b'Outro')], max_length=1, verbose_name=b'Staff'),
        ),
    ]
