# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0002_adicionalink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adicionalink',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='adicionalink',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
