# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0003_auto_20160101_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicionalink',
            name='choice_text1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adicionalink',
            name='text',
            field=models.TextField(),
        ),
    ]
