# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0003_initiallistquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiallistquestion',
            name='select',
            field=models.IntegerField(default=0),
        ),
    ]
