# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0003_auto_20160408_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
