# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0003_auto_20160404_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meuespacoartigo',
            name='address',
        ),
        migrations.AddField(
            model_name='message',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name=b'Endere\xc3\xa7o'),
        ),
    ]
