# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0004_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='projeto',
            field=models.CharField(choices=[('pdp-u', 'pdp-u'), ('RCB', 'RCB')], default=1, max_length=50, verbose_name=b'Projeto'),
            preserve_default=False,
        ),
    ]
