# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0004_initiallistquestion_select'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='publ_date',
        ),
    ]
