# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 23:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agora', '0004_auto_20160101_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adicionalink',
            name='choice_text1',
        ),
        migrations.AddField(
            model_name='adicionalink',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adicionalink',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
