# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0005_question_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_status',
            field=models.CharField(choices=[(b'n', b'N\xc3\xa3o publicado'), (b'p', b'Publicado')], default=b'n', max_length=1, verbose_name=b'Estado da quest\xc3\xa3o'),
        ),
    ]
