# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0005_auto_20160101_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adicionalink',
            old_name='published_date',
            new_name='data_publicacao',
        ),
        migrations.RenameField(
            model_name='adicionalink',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='adicionalink',
            name='author',
        ),
        migrations.RemoveField(
            model_name='adicionalink',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='adicionalink',
            name='text',
        ),
        migrations.AddField(
            model_name='adicionalink',
            name='url',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
