# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0007_auto_20160307_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academic_registry',
            field=models.IntegerField(default='9999', verbose_name='Registro acadêmico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, default='curso', max_length=40, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='user',
            name='institute',
            field=models.CharField(blank=True, default='instituto', max_length=40, verbose_name='Instituto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_start',
            field=models.IntegerField(blank=True, default='9999', verbose_name='Ano de ingresso'),
        ),
    ]
