# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lista_de_questions_respondidas',
            field=models.CommaSeparatedIntegerField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
