# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0008_userprofile_lista_de_questions_respondidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lista_de_questions_respondidas',
            field=models.IntegerField(),
        ),
    ]
