# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0008_auto_20160307_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('1', 'Conheça'), ('2', 'Resultados'), ('3', 'Comunidade'), ('4', 'Participe')], max_length=1, verbose_name='Tipo')),
                ('publ_date', models.DateTimeField(verbose_name='Data de publicação')),
                ('message', models.CharField(max_length=500, verbose_name='Recado')),
            ],
        ),
    ]
