# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 19:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agora', '0009_auto_20160105_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestoesRespondidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao', models.IntegerField()),
                ('publications', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
