# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='published',
            field=models.CharField(default='Não', max_length=3, verbose_name='Publicado?'),
        ),
    ]
