# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0010_message_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(default='Não', max_length=3, verbose_name='Condição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agora.User')),
            ],
        ),
    ]
