# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0011_termo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='condition',
            field=models.CharField(default='Não', max_length=3, verbose_name='Condição'),
        ),
    ]
