# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0011_auto_20160105_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='questoesrespondidas',
            name='usuario',
            field=models.ManyToManyField(to='agora.Usuario'),
        ),
    ]
