# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0012_auto_20160105_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questoesrespondidas',
            name='questao',
            field=models.CharField(max_length=200),
        ),
    ]
