# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0012_user_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='user',
            field=models.CharField(max_length=300),
        ),
    ]
