# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0013_auto_20160319_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='condition',
        ),
    ]
