# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-19 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0014_remove_user_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agora.User'),
        ),
    ]
