# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0015_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='submeter_resultados',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
