# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0016_question_submeter_resultados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='submeter_resultados',
        ),
        migrations.AddField(
            model_name='question',
            name='permissao',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
