# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0017_auto_20160111_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='permissao',
        ),
    ]
