# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0018_remove_question_permissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('n', 'Não publicado'), ('p', 'Publicado')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
