# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0019_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='nickname',
            field=models.CharField(blank=True, max_length=40, verbose_name='Apelido'),
        ),
    ]
