# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0019_question_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='permissao',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
