# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0020_question_permissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.AddField(
            model_name='question',
            name='resultado',
            field=models.CharField(choices=[('n', 'Não publicado'), ('p', 'Publicado')], default='n', max_length=1),
        ),
    ]
