# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0020_question_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=40, verbose_name='Apelido'),
        ),
    ]
