# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 01:29
from __future__ import unicode_literals

import agora.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0021_auto_20160320_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeuEspacoArtigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=20, verbose_name='Categoria')),
                ('publ_date', models.DateTimeField(verbose_name='Data de publicação')),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('comentario', models.CharField(blank=True, max_length=200, verbose_name='Comentário')),
                ('arquivo', models.FileField(blank=True, max_length=20000, upload_to='static/agora', validators=[agora.models.MeuEspacoArtigo.validate_file_extension])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agora.User')),
            ],
        ),
    ]
