# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 17:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agora', '0021_auto_20160111_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='usuario_que_votou',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
