# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0022_meuespacoartigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='meuespacoartigo',
            name='secao',
            field=models.CharField(blank=True, max_length=30, verbose_name='Seção'),
        ),
    ]
