# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0023_meuespacoartigo_secao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuespacoartigo',
            name='user',
            field=models.CharField(blank=True, max_length=200, verbose_name='Usuario'),
        ),
    ]
