# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0026_auto_20160114_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votodousuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='votodousuario',
            name='questao',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votodousuario',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agora.Usuario'),
            preserve_default=False,
        ),
    ]
