# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0030_remove_choice_usuario_que_votou'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='accepted_eula',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_animal',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ano_de_ingresso',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='curso',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='faculdade',
            field=models.CharField(default=datetime.datetime(2016, 1, 16, 19, 17, 56, 534031, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
