# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0036_auto_20160116_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
