# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 20:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agora', '0037_auto_20160116_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_de_ingresso', models.CharField(max_length=20)),
                ('faculdade', models.CharField(max_length=20)),
                ('curso', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ano_de_ingresso',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='faculdade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
