# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0038_auto_20160116_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='faculdade',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
