# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0039_usuario_faculdade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='faculdade',
        ),
        migrations.AddField(
            model_name='votodousuario',
            name='faculdade',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
