# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0045_auto_20160118_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='faculdade',
            field=models.CharField(default='faculdade', max_length=20),
        ),
        migrations.AlterField(
            model_name='votodousuario',
            name='faculdade',
            field=models.CharField(max_length=20),
        ),
    ]
