# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0047_auto_20160118_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='0000000', editable=False, max_length=200),
        ),
    ]
