# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0048_auto_20160119_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
