# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0051_auto_20160119_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
