# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0052_auto_20160119_1439'),
    ]

   