# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 16:52
from __future__ import unicode_literals

import agora.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0053_auto_20160119_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ID',
        ),
        migrations.AddField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=agora.models.Question.contact_default, max_length=200),
        ),
    ]
