# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0056_auto_20160119_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='contact_default', max_length=200),
        ),
    ]
