# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 19:59
from __future__ import unicode_literals

import agora.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0057_auto_20160119_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=agora.models.Question.define_primary_key, max_length=200),
        ),
    ]
