# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 17:12
from __future__ import unicode_literals

import agora.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0058_auto_20160119_1759'),
    ]

