# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 17:22
from __future__ import unicode_literals

import agora.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0059_auto_20160122_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=agora.models.Question.define_next, max_length=200),
        ),
    ]
