# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0060_auto_20160122_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tipo',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
