# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0061_question_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tipo',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('1', 'One choice'), ('2', 'Multipla Escolha'), ('3', 'Texto')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
