# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 19:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0062_auto_20160125_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 25, 19, 31, 48, 355699, tzinfo=utc), verbose_name='Data de expiração'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Data de publicação'),
        ),
    ]
