# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-25 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0063_auto_20160125_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='expire_date',
            new_name='expiration_date',
        ),
    ]
