# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0064_auto_20160125_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='permissao',
            field=models.IntegerField(default=0),
        ),
    ]
