# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0065_auto_20160126_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdicionaLink',
        ),
    ]
