# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0066_delete_adicionalink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
