# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0068_auto_20160201_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'questão', 'verbose_name_plural': 'questões'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='expiration_date',
            new_name='exp_date',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_status',
            field=models.CharField(choices=[('u', 'Não publicado'), ('p', 'Publicado')], default='u', max_length=1, verbose_name='Estado da resposta'),
        ),
        migrations.AddField(
            model_name='question',
            name='days',
            field=models.IntegerField(choices=[(1, '1 dia'), (7, '1 semana'), (30, '1 mês'), (365, '1 ano'), (3650, 'Indeterminado')], default=3650, verbose_name='Tempo para expirar'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_status',
            field=models.CharField(choices=[('u', 'Não publicado'), ('p', 'Publicado')], default='p', max_length=1, verbose_name='Estado da questão'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Questão'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('1', 'Única'), ('2', 'Múltipla'), ('3', 'Texto')], max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='question',
            name='resultado',
            field=models.CharField(choices=[('u', 'Não publicado'), ('p', 'Publicado')], default='u', max_length=1),
        ),
    ]
