# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agora', '0069_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_start', models.IntegerField(blank=True)),
                ('department', models.CharField(blank=True, max_length=40)),
                ('course', models.CharField(blank=True, max_length=40)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('academic_registry', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'usuários',
                'verbose_name': 'usuário',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'escolha', 'verbose_name_plural': 'escolhas'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agora.User'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
