# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0070_auto_20160216_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='answers',
            field=models.ManyToManyField(related_name='_user_answers_+', through='agora.Answer', to='agora.Question'),
        ),
    ]
