# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0072_auto_20160216_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='resultado',
            field=models.CharField(choices=[('n', 'Não publicado'), ('p', 'Publicado')], default='u', max_length=1),
        ),
    ]
