# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 20:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0072_auto_20160204_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotoDoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(max_length=200)),
                ('usuario', models.ManyToManyField(to='agora.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='QuestoesRespondidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao', models.IntegerField()),
                ('publications', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_de_ingresso', models.CharField(max_length=20)),
                ('faculdade', models.CharField(max_length=20)),
                ('curso', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'questão', 'verbose_name_plural': 'questões'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agora.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer_status',
            field=models.CharField(choices=[('u', 'Não publicado'), ('p', 'Publicado')], default='u', max_length=1, verbose_name='Estado da resposta'),
        ),
        migrations.AddField(
            model_name='question',
            name='days',
            field=models.IntegerField(choices=[(1, '1 dia'), (7, '1 semana'), (30, '1 mês'), (365, '1 ano'), (3650, 'Indeterminado')], default=3650, verbose_name='Tempo para expirar'),
        ),
        migrations.AddField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 4, 20, 52, 44, 9745, tzinfo=utc), verbose_name='Data de expiração'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_status',
            field=models.CharField(choices=[('u', 'Não publicado'), ('p', 'Publicado')], default='p', max_length=1, verbose_name='Estado da questão'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('o', 'Única'), ('m', 'Múltipla'), ('t', 'Texto')], default='o', max_length=1, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='Questão'),
        ),
        migrations.DeleteModel(
            name='QuestoesRespondidas',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='VotoDoUsuario',
        ),
    ]
