# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0073_auto_20160216_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='expiration_date',
            new_name='exp_date',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('1', 'One choice'), ('2', 'Multipla Escolha'), ('3', 'Texto')], max_length=1, verbose_name='Tipo'),
        ),
    ]
