# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 00:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0073_auto_20160204_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'escolha', 'verbose_name_plural': 'escolhas'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
