# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0074_auto_20160216_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='days',
            field=models.IntegerField(choices=[(1, '1 dia'), (7, '1 semana'), (30, '1 mês'), (365, '1 ano'), (3650, 'Indeterminado')], default=3650, verbose_name='Tempo para expirar'),
        ),
    ]
