# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0075_question_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_status',
            field=models.CharField(choices=[('n', 'Não publicado'), ('p', 'Publicado')], default='n', max_length=1, verbose_name='Estado da resposta'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_status',
            field=models.CharField(choices=[('n', 'Não publicado'), ('p', 'Publicado')], default='p', max_length=1, verbose_name='Estado da questão'),
        ),
    ]
