# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0076_auto_20160216_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questoesrespondidas',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='votodousuario',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'questão', 'verbose_name_plural': 'questões'},
        ),
        migrations.DeleteModel(
            name='QuestoesRespondidas',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='VotoDoUsuario',
        ),
    ]
