# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agora', '0077_auto_20160216_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
