# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-13 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0016_auto_20161124_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelaranking',
            name='betweenness_norm',
            field=models.FloatField(default=1, verbose_name='Betweenness_norm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabelaranking',
            name='closeness_norm',
            field=models.FloatField(default=1, verbose_name='Closeness_norm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabelaranking',
            name='grau_norm',
            field=models.FloatField(default=1, verbose_name='Grau_norm'),
            preserve_default=False,
        ),
    ]
