# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0021_auto_20170319_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesosEAlpha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_grau', models.FloatField(verbose_name='Peso_Grau')),
                ('p_betw', models.FloatField(verbose_name='Peso_Betweenness')),
                ('p_close', models.FloatField(verbose_name='Peso_Closeness')),
                ('alpha', models.FloatField(verbose_name='Alpha')),
            ],
        ),
    ]
