# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0025_dadospreproc_corretor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelaranking',
            name='indice',
        ),
        migrations.AddField(
            model_name='tabelaranking',
            name='potenciacao',
            field=models.FloatField(default=1, verbose_name='potencia\xe7\xe3o'),
            preserve_default=False,
        ),
    ]
