# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0031_extracaonew'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracaonew',
            name='tema',
            field=models.TextField(default=1, verbose_name='Tema'),
            preserve_default=False,
        ),
    ]
