# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0032_extracaonew_tema'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosExtracaoNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.TextField(verbose_name='Tema')),
                ('protofrase', models.TextField(verbose_name='Proto Frase')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
            ],
        ),
    ]
