# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0037_auto_20170525_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosMapeamentoEExtracao',
        ),
        migrations.DeleteModel(
            name='DadosProtofrases',
        ),
        migrations.DeleteModel(
            name='MapeamentoEExtracaoTextos',
        ),
        migrations.DeleteModel(
            name='ParagrafosExtraidos',
        ),
        migrations.DeleteModel(
            name='ProtoFrase',
        ),
        migrations.DeleteModel(
            name='Sorteio',
        ),
    ]
