# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0039_testapalavra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testapalavra',
            name='resultado',
            field=models.TextField(verbose_name='Resultado'),
        ),
    ]
