# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0041_dadospreproc_flag_testapalavra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeSubstantivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.TextField(verbose_name='palavra')),
                ('substantivo', models.TextField(verbose_name='Substantivo')),
            ],
        ),
    ]
