# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0044_auto_20170531_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosDeAjuste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField(default=1, verbose_name='Identificacao')),
                ('k_betweenness', models.IntegerField(default=100, verbose_name='K_betweenness')),
                ('dr_delta_min', models.IntegerField(default=5, verbose_name='Delta_distancia_relativa_min')),
                ('f_corte', models.IntegerField(default=10, verbose_name='Freq_corte_nos_com_dr_min')),
                ('f_min_bigramas', models.IntegerField(default=50, verbose_name='Freq_min_de_bigramas')),
            ],
        ),
    ]
