# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0007_user_projeto'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='projeto',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='agoraunicamp.Projeto'),
            preserve_default=False,
        ),
    ]
