# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='pub_date',
            field=models.DateTimeField(verbose_name=b'Data de publica\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=50, verbose_name=b'T\xc3\xadtulo'),
        ),
    ]
