# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20160404_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='published',
            field=models.CharField(default=b'N\xc3\xa3o', max_length=3, verbose_name=b'Publicado?'),
        ),
    ]
