# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20160223_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='topic_user',
            new_name='user',
        ),
    ]
