# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 17:28
from __future__ import unicode_literals

import conheca.models
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('article', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('destaque', models.CharField(default='Não', max_length=3)),
                ('questao_associada', models.CommaSeparatedIntegerField(blank=True, max_length=100)),
                ('address', models.CharField(default=conheca.models.Article.get_address, max_length=200)),
                ('published', models.CharField(default='Não', max_length=3)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('url_title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('session', models.CharField(choices=[('1', 'Sobre o PDPU'), ('2', 'Outras informações')], max_length=1)),
                ('position', models.CharField(default=conheca.models.Topic.get1_pk1, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conheca.Topic'),
        ),
    ]
