# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='projeto',
            field=models.CharField(choices=[('PDP-U', 'PDP-U')], max_length=50, verbose_name=b'Projeto'),
        ),
        migrations.AlterField(
            model_name='topico',
            name='projeto',
            field=models.CharField(choices=[('PDP-U', 'PDP-U')], max_length=50, verbose_name=b'Projeto'),
        ),
    ]
