# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 01:20
from __future__ import unicode_literals

import conheca.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('url_title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('session', models.CharField(choices=[('1', 'Sobre o PDPU'), ('2', 'Outras informações')], max_length=1)),
                ('position', models.CharField(default=conheca.models.Topic.get1_pk1, max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='AdicionaLink',
        ),
        migrations.RemoveField(
            model_name='article',
            name='spot',
        ),
        migrations.AddField(
            model_name='article',
            name='address',
            field=models.CharField(default=conheca.models.Article.get_address, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='destaque',
            field=models.CharField(default='Não', max_length=3),
        ),
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.CharField(default='Não', max_length=3),
        ),
        migrations.AddField(
            model_name='article',
            name='questao_associada',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conheca.Topic'),
        ),
    ]
