# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topico',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
