# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='projeto',
            field=models.CharField(blank=True, choices=[(1, 'Plano Diretor Participativo'), (2, 'Reforma do Ciclo B\xe1sico')], max_length=1, verbose_name=b'Projeto'),
        ),
    ]
