# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='spot',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
