# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 01:42
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0002_auto_20160201_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=tinymce.models.HTMLField(),
        ),
    ]
