# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 02:14
from __future__ import unicode_literals

import conheca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0002_auto_20160205_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topico',
            name='position',
            field=models.IntegerField(default=conheca.models.Topico.position_det),
        ),
    ]
