# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0003_auto_20160128_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='spot',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
