# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0004_auto_20160128_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='spot',
        ),
        migrations.AddField(
            model_name='article',
            name='destaque',
            field=models.CharField(default='Não', max_length=3),
        ),
    ]
