# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-28 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0005_auto_20160128_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='questao_associada',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
