# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0006_article_questao_associada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='questao_associada',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=100),
        ),
    ]
