# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0008_auto_20160129_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
