# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0009_auto_20160129_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='url_title',
            field=models.CharField(default=datetime.datetime(2016, 1, 29, 17, 43, 6, 366300, tzinfo=utc), max_length=1000),
            preserve_default=False,
        ),
    ]
