# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0010_link_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='session',
            field=models.CharField(choices=[('1', 'Sobre o PDPU'), ('2', 'Outras informações')], default=datetime.datetime(2016, 1, 29, 19, 24, 23, 2067, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
    ]
