# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 21:38
from __future__ import unicode_literals

import conheca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0011_topic_session'),
    ]

    