# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0013_auto_20160129_1940'),
    ]

  