# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0014_auto_20160129_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='address',
            field=models.CharField(default=datetime.datetime(2016, 1, 29, 21, 44, 34, 602094, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
