# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0015_article_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='address',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
