# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 21:47
from __future__ import unicode_literals

import conheca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0016_auto_20160129_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='address',
            field=models.CharField(default=conheca.models.Article.get_address, max_length=200),
        ),
    ]
