# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-29 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0017_auto_20160129_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.CharField(default='Não', max_length=3),
        ),
    ]
