# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 00:21
from __future__ import unicode_literals

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0018_article_published'),
    ]

