# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0019_topic_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='position',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
