# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 00:24
from __future__ import unicode_literals

import conheca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conheca', '0020_topic_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='position',
            field=models.CharField(default=conheca.models.Topic.get1_pk1, max_length=200),
        ),
    ]
