# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 00:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import resultados.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agora', '0068_auto_20160201_1447'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Geral'), ('2', 'Questão')], default='1', max_length=10)),
                ('conteudo', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Resultado e Análise')),
                ('publ_date', models.DateTimeField(null=True)),
                ('destaque', models.CharField(default='Não', max_length=3)),
                ('address', models.CharField(default=resultados.models.Relatorio.get_address, max_length=200)),
                ('published', models.CharField(default='Não', max_length=3)),
                ('publ_historico', models.CharField(default='Não', max_length=3)),
                ('questao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agora.Question')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
