# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-24 00:32
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('agora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likedislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('relatorio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Geral'), ('2', 'Questão')], default='1', max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Resultado e Análise')),
                ('publ_date', models.DateTimeField(null=True)),
                ('destaque', models.CharField(default='Não', max_length=3)),
                ('address', models.CharField(max_length=200)),
                ('published', models.CharField(default='Não', max_length=3)),
                ('publhistorico', models.CharField(default='Não', max_length=3)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('questao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agora.Question')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
