# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 00:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatorio',
            old_name='publ_historico',
            new_name='publhistorico',
        ),
    ]
