# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 00:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_auto_20160211_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='titulo',
            field=models.CharField(default=datetime.datetime(2016, 2, 12, 0, 28, 39, 103215, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
