# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0005_auto_20160212_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='like',
        ),
        migrations.AddField(
            model_name='likedislike',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='likedislike',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
