# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0007_auto_20160212_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
