# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0008_auto_20160212_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='relatorio',
            field=models.IntegerField(),
        ),
    ]
