# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 01:34
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=200, null=True)),
                ('answer_date', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostas',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'escolha',
                'verbose_name_plural': 'escolhas',
            },
        ),
        migrations.CreateModel(
            name='Curtir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10, verbose_name='Curtir/N\xe3o Curtir')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(default='1', max_length=1, verbose_name='Etapa')),
                ('name', models.CharField(default='Ideias', max_length=100, verbose_name='Nome da etapa')),
                ('header_txt', models.TextField(default='null', verbose_name='Cabe\xe7alho')),
                ('objetivo_txt', models.TextField(default='null', verbose_name='Objetivo')),
                ('participar_txt', models.TextField(default='null', verbose_name='Como participar')),
                ('resultado_txt', models.TextField(default='null', verbose_name='Resultado')),
            ],
        ),
        migrations.CreateModel(
            name='MeuEspaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=100, verbose_name='Projeto')),
                ('user', models.CharField(blank=True, max_length=200, verbose_name='Usuario')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria')),
                ('publ_date', models.DateTimeField(verbose_name='Data de publica\xe7\xe3o')),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('comentario', models.CharField(max_length=1000, verbose_name='Coment\xe1rio')),
                ('secao', models.CharField(blank=True, max_length=30, null=True, verbose_name='Se\xe7\xe3o')),
                ('arquivo', models.FileField(blank=True, max_length=2000000, null=True, upload_to=b'C:\\virtual-agora\\media')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Projeto')),
                ('sigla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla')),
                ('etapa_prj', models.CharField(default='1', max_length=1, verbose_name='Etapa')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposta_text', models.TextField(verbose_name='Proposta')),
                ('ranking', models.CharField(default='1', max_length=5, verbose_name='Ranking')),
                ('indice', models.IntegerField(default=1000, verbose_name='Indice')),
                ('curtidas', models.IntegerField(default=0, verbose_name='Curtidas')),
                ('naocurtidas', models.IntegerField(default=0, verbose_name='N\xe3o Curtidas')),
            ],
            options={
                'verbose_name': 'proposta',
                'verbose_name_plural': 'propostas',
            },
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publ_date', models.DateTimeField(blank=True, verbose_name='Data de publica\xe7\xe3o')),
                ('published', models.CharField(choices=[('sim', 'sim'), ('nao', 'nao')], default='nao', max_length=3, verbose_name='Publicar imediatamente?')),
                ('etapa_publ', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1, verbose_name='Etapa que ser\xe1 publicado')),
                ('address', models.CharField(default='Preenchimento automatico', max_length=200, verbose_name='Endere\xe7o')),
            ],
        ),
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(default='Nao', max_length=10, verbose_name='Condi\xe7\xe3o')),
            ],
        ),
        migrations.CreateModel(
            name='TopicAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='')),
                ('answer_date', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name': 'comentario',
                'verbose_name_plural': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='TopicAnswerReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='')),
                ('answer_date', models.DateTimeField(editable=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicanswerreply', to='agoraunicamp.TopicAnswer')),
            ],
            options={
                'verbose_name': 'R\xe9plica',
                'verbose_name_plural': 'R\xe9plicas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(default='agoraunicamp/media/img/no-avatar.jpg', upload_to='agoraunicamp/media/img/')),
                ('primeiro_nome', models.CharField(blank=True, max_length=40, verbose_name='Primeiro nome')),
                ('ultimo_nome', models.CharField(blank=True, max_length=100, verbose_name='Sobrenome')),
                ('nome_completo', models.CharField(blank=True, max_length=200, verbose_name='Nome Completo')),
                ('staff', models.CharField(blank=True, choices=[('1', 'Professor'), ('2', 'Funcionario'), ('3', 'Aluno-Graduacao'), ('4', 'Aluno-Mestrado'), ('5', 'Aluno-Doutorado'), ('6', 'Aluno-Especial'), ('7', 'Aluno-Lato'), ('8', 'outro')], max_length=1, verbose_name='Staff')),
                ('institute', models.CharField(blank=True, default='instituto', max_length=40, verbose_name='Instituto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nickname', models.CharField(blank=True, max_length=40, verbose_name='Apelido')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agoraunicamp.Projeto')),
            ],
            options={
                'verbose_name': 'usu\xe1rio',
                'verbose_name_plural': 'usu\xe1rios',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('publicacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agoraunicamp.Publicacao')),
                ('title', models.CharField(max_length=200, verbose_name='T\xedtulo do artigo')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descri\xe7\xe3o')),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
            },
            bases=('agoraunicamp.publicacao',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('publicacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agoraunicamp.Publicacao')),
                ('question_type', models.CharField(choices=[('1', 'One choice'), ('2', 'Multipla Escolha'), ('3', 'Texto'), ('4', 'Popostas')], max_length=1, verbose_name='Tipo')),
                ('question_text', models.CharField(max_length=200, verbose_name='T\xedtulo da Quest\xe3o')),
                ('exp_date', models.DateTimeField(verbose_name='Data de expira\xe7\xe3o')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'quest\xe3o',
                'verbose_name_plural': 'quest\xf5es',
            },
            bases=('agoraunicamp.publicacao',),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('publicacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agoraunicamp.Publicacao')),
                ('tipo', models.CharField(choices=[('1', 'Resultado Geral (n\xe3o associado a alguma quest\xe3o)'), ('2', 'Resultado Espec\xedfico (assciado a uma quest\xe3o)')], default='0', max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('conteudo', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Resultado e An\xe1lise')),
                ('grafico', models.CharField(choices=[('0', 'Sem Gr\xe1fico ou Tabela'), ('1', 'Gr\xe1fico de  Barras'), ('2', 'Gr\xe1fico de Pizza'), ('3', 'Tabela de Propostas')], default='1', max_length=10)),
                ('filtro_staff', models.CharField(choices=[('1', 'Professor'), ('2', 'Funcionario'), ('3', 'Aluno-Graduacao'), ('4', 'Aluno-Mestrado'), ('5', 'Aluno-Doutorado'), ('6', 'Aluno-Especial'), ('7', 'Aluno-Lato'), ('8', 'outro'), ('9', 'todos')], default='9', max_length=3)),
                ('arquivo', models.CharField(default='null', max_length=200)),
                ('propostas_org', models.CharField(choices=[('0', 'N\xe3o \xe9 resultado do tipo Propostas'), ('1', 'Da Quest\xe3o Associada (certifique-se que a Quest\xe3o \xe9 do tipo "Propostas"'), ('2', 'Do Campo "PROPOSTAS" abaixo')], default='0', max_length=3, verbose_name='Origem')),
                ('questao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agoraunicamp.Question')),
            ],
            bases=('agoraunicamp.publicacao',),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('publicacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agoraunicamp.Publicacao')),
                ('title', models.CharField(max_length=50, verbose_name='T\xedtulo')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'debate',
                'verbose_name_plural': 'debates',
            },
            bases=('agoraunicamp.publicacao',),
        ),
        migrations.AddField(
            model_name='topicanswerreply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicanswerreply', to='agoraunicamp.User'),
        ),
        migrations.AddField(
            model_name='topicanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicanswer', to='agoraunicamp.User'),
        ),
        migrations.AddField(
            model_name='termo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_termo', to='agoraunicamp.User'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agoraunicamp.Projeto'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agoraunicamp.Projeto', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='curtir',
            name='proposta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtir', to='agoraunicamp.Proposta'),
        ),
        migrations.AddField(
            model_name='curtir',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtir', to='agoraunicamp.User'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice', to='agoraunicamp.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='agoraunicamp.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='question_answer',
            field=models.ManyToManyField(related_name='question_answer', through='agoraunicamp.Answer', to='agoraunicamp.Question'),
        ),
        migrations.AddField(
            model_name='user',
            name='topic_answer',
            field=models.ManyToManyField(related_name='topic_answer', through='agoraunicamp.TopicAnswer', to='agoraunicamp.Topic'),
        ),
        migrations.AddField(
            model_name='topicanswer',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicanswer', to='agoraunicamp.Topic'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposta', to='agoraunicamp.Relatorio'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agoraunicamp.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='agoraunicamp.Question'),
        ),
    ]
