# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(default='N\xe3o', max_length=3, verbose_name='Condi\xe7\xe3o')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_termo', to='agoraunicamp.User')),
            ],
        ),
    ]
