# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-27 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('agoraunicamp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publ_date', models.DateTimeField(blank=True, verbose_name='Data de publica\xe7\xe3o')),
                ('published', models.CharField(default='nao', max_length=3, verbose_name='Publicado?')),
                ('etapa_publ', models.CharField(default='1', max_length=1, verbose_name='Etapa')),
                ('address', models.CharField(default='Preenchimento automatico', max_length=200, verbose_name='Endere\xe7o')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agoraunicamp.Projeto')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='address',
        ),
        migrations.RemoveField(
            model_name='article',
            name='etapa_publ',
        ),
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.RemoveField(
            model_name='article',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='article',
            name='publ_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='address',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='etapa_publ',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='projeto',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='publ_date',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='published',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='publicacao_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agoraunicamp.Publicacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relatorio',
            name='publicacao_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agoraunicamp.Publicacao'),
            preserve_default=False,
        ),
    ]
