# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-05 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agoraunicamp.Projeto'),
        ),
    ]
