# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0002_termo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeuEspaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=200, verbose_name='Usuario')),
                ('categoria', models.CharField(blank=True, max_length=20, verbose_name='Categoria')),
                ('publ_date', models.DateTimeField(verbose_name='Data de publica\xe7\xe3o')),
                ('link', models.URLField(blank=True, max_length=1000)),
                ('comentario', models.CharField(blank=True, max_length=200, verbose_name='Coment\xe1rio')),
                ('secao', models.CharField(blank=True, max_length=30, verbose_name='Se\xe7\xe3o')),
                ('arquivo', models.FileField(blank=True, max_length=2000000, upload_to=b'C:\\virtual-agora\\media')),
            ],
        ),
    ]
