# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0002_auto_20160411_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuespaco',
            name='projeto',
            field=models.CharField(max_length=20, verbose_name='Projeto'),
        ),
    ]
