# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-27 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0003_auto_20180526_2238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etapas',
            new_name='Etapa',
        ),
    ]
