# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0003_etapa_termino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='etapa_prj',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1, verbose_name='Etapa'),
        ),
    ]
