# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 18:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0004_auto_20180605_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='')),
                ('opcoes', models.CharField(choices=[('1', 'TODOS'), ('2', 'ESPEC\xcdFICO')], default='1', max_length=15, verbose_name='Destinat\xe1rio')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to='agoraunicamp.User')),
            ],
        ),
    ]
