# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-28 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0004_auto_20180527_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('1', 'One choice'), ('2', 'Multipla Escolha'), ('3', 'Texto'), ('4', 'Popostas')], max_length=1, verbose_name='Tipo'),
        ),
    ]
