# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 23:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0005_projeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='nome',
            new_name='projeto',
        ),
    ]
