# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0005_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name': 'Enviar Email', 'verbose_name_plural': 'Enviar Emails'},
        ),
    ]
