# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0006_auto_20160408_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projeto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Projeto'),
        ),
    ]
