# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0006_topicanswerreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicanswer',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='agoraunicamp.Topic'),
        ),
    ]
