# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 19:10
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0006_auto_20180606_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={},
        ),
        migrations.AddField(
            model_name='email',
            name='assunto',
            field=models.TextField(default=1, verbose_name='Assunto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Mensagem'),
        ),
    ]
