# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0007_user_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='projeto',
            field=models.CharField(choices=[('pdp-u', 'pdp-u'), ('RCB', 'RCB')], default=1, max_length=50, verbose_name='Projeto'),
            preserve_default=False,
        ),
    ]
