# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0008_auto_20180528_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicanswer', to='agoraunicamp.User'),
        ),
    ]
