# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-29 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0010_auto_20180529_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicanswerreply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicanswerreply', to='agoraunicamp.TopicAnswer'),
        ),
    ]
