# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-30 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0012_user_nome_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/img/no-avatar.jpg', upload_to='media/img/'),
        ),
    ]
