# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-30 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0014_auto_20180529_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='agoraunicamp/media/img/no-avatar.jpg', upload_to='agoraunicamp/media/img/'),
        ),
    ]
