# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-02 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0015_auto_20180529_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='filtro_staff',
            field=models.CharField(choices=[('1', 'Professor'), ('2', 'Funcionario'), ('3', 'Aluno-Graduacao'), ('4', 'Aluno-Mestrado'), ('5', 'Aluno-Doutorado'), ('6', 'Aluno-Especial'), ('7', 'Aluno-Lato'), ('8', 'outro'), ('9', 'todos')], default='9', max_length=3),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='grafico',
            field=models.CharField(choices=[('1', 'Barras'), ('2', 'Pizza'), ('3', 'Propostas')], default='1', max_length=10),
        ),
    ]
