# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-02 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0016_auto_20180602_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='arquivo',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='tipo',
            field=models.CharField(choices=[('1', 'Resultado Geral, sem gr\xe1fico'), ('2', 'Quest\xe3o - gera gr\xe1fico')], default='1', max_length=10),
        ),
    ]
