# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-03 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0018_auto_20180603_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposta',
            options={'verbose_name': 'proposta', 'verbose_name_plural': 'propostas'},
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='propostas_org',
            field=models.CharField(choices=[('0', 'N\xe3o \xe9 resultado do tipo Propostas'), ('1', 'Da Quet\xe3o'), ('2', 'Dos campos abaixo')], default='0', max_length=3, verbose_name='Caso tenha selecionado PROPOSTAS, escolha a origem'),
        ),
    ]
