# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-03 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0019_auto_20180603_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='relatorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposta', to='agoraunicamp.Relatorio'),
        ),
    ]
