# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-03 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0020_auto_20180603_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='indice',
            field=models.CharField(default='1', max_length=10, verbose_name='Indice'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='ranking',
            field=models.CharField(default='1', max_length=5, verbose_name='Ranking'),
        ),
    ]
