# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-03 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0021_auto_20180603_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curtir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtir', to='agoraunicamp.Proposta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtir', to='agoraunicamp.User')),
            ],
        ),
    ]
