# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-03 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0023_proposta_curtidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtir',
            name='tipo',
            field=models.CharField(default=1, max_length=10, verbose_name='Curtir/N\xe3o Curtir'),
            preserve_default=False,
        ),
    ]
