# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-03 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0024_curtir_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='naocurtidas',
            field=models.IntegerField(default=0, verbose_name='N\xe3o Curtidas'),
        ),
    ]
