# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-04 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agoraunicamp', '0026_auto_20180603_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='indice',
            field=models.IntegerField(default=1000, max_length=10, verbose_name='Indice'),
        ),
    ]
