# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-14 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0017_auto_20170313_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelaranking',
            name='indice',
            field=models.FloatField(default=0, verbose_name='indice'),
            preserve_default=False,
        ),
    ]
