# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-19 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0018_tabelaranking_indice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_grau', models.IntegerField(verbose_name='porcentagem_grau')),
                ('p_clos', models.IntegerField(verbose_name='porcentagem_closeness')),
                ('p_bet', models.IntegerField(verbose_name='porcentagem_betweeness')),
                ('temas_pre_selecionados', models.TextField(verbose_name='d_p')),
                ('temas_selecionados', models.TextField(verbose_name='d_plc')),
                ('dr', models.IntegerField(verbose_name='distancia_relativa_minima')),
                ('k', models.IntegerField(verbose_name='porcentagem_minima_dos_nos_totais_na_cauda_longa')),
                ('fb', models.IntegerField(verbose_name='frequencia_do_bigrama')),
            ],
        ),
    ]
