# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0019_temas'),
    ]

    operations = [
        migrations.AddField(
            model_name='temas',
            name='delta',
            field=models.IntegerField(default=1, verbose_name='Delta entre vertices'),
            preserve_default=False,
        ),
    ]
