# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0020_temas_delta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temas',
            old_name='k',
            new_name='f',
        ),
        migrations.RemoveField(
            model_name='temas',
            name='dr',
        ),
    ]
