# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0023_auto_20170331_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temas',
            name='p_bet',
            field=models.FloatField(verbose_name='porcentagem_betweeness'),
        ),
        migrations.AlterField(
            model_name='temas',
            name='p_clos',
            field=models.FloatField(verbose_name='porcentagem_closeness'),
        ),
        migrations.AlterField(
            model_name='temas',
            name='p_grau',
            field=models.FloatField(verbose_name='porcentagem_grau'),
        ),
    ]
