# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0024_auto_20170404_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospreproc',
            name='corretor',
            field=models.CharField(default='off', max_length=10, verbose_name='Corretor'),
        ),
    ]
