# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0026_auto_20170513_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosSelecaoTemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.IntegerField(verbose_name='distancia_relativa_minima')),
                ('f', models.IntegerField(verbose_name='porcentagem_minima_dos_nos_totais_na_cauda_longa')),
                ('fb', models.IntegerField(verbose_name='frequencia_do_bigrama')),
            ],
        ),
        migrations.DeleteModel(
            name='Temas',
        ),
    ]
