# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0027_auto_20170521_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosselecaotemas',
            name='p_bet',
            field=models.FloatField(default=0, verbose_name='Peso Closeness'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadosselecaotemas',
            name='p_clos',
            field=models.FloatField(default=0, verbose_name='Peso Betweeness'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadosselecaotemas',
            name='p_grau',
            field=models.FloatField(default=0, verbose_name='Peso Graus'),
            preserve_default=False,
        ),
    ]
