# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0028_auto_20170521_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtoFrasesNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protofrase', models.TextField(verbose_name='Proto Frase')),
            ],
        ),
        migrations.CreateModel(
            name='TemasNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.TextField(verbose_name='Tema')),
            ],
        ),
    ]
