# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0033_dadosextracaonew'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracaonew',
            name='sentenca',
            field=models.TextField(default=1, verbose_name='Sentenca'),
            preserve_default=False,
        ),
    ]
