# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-24 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0034_extracaonew_sentenca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracaonew',
            name='sentenca',
        ),
        migrations.AddField(
            model_name='dadosextracaonew',
            name='sentenca',
            field=models.TextField(default=1, verbose_name='Sentenca'),
            preserve_default=False,
        ),
    ]
