# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0035_auto_20170524_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='temasnew',
            name='irt',
            field=models.FloatField(default=1, verbose_name='IRT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temasnew',
            name='irt_p',
            field=models.FloatField(default=1, verbose_name='IRT%'),
            preserve_default=False,
        ),
    ]
