# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0038_auto_20170530_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestaPalavra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.TextField(verbose_name='palavra')),
                ('condicao', models.TextField(verbose_name='Condicao')),
                ('resultado', models.IntegerField(verbose_name='Resultado')),
            ],
        ),
    ]
