# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0040_auto_20170530_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospreproc',
            name='flag_testapalavra',
            field=models.TextField(default=1, verbose_name='Flag'),
            preserve_default=False,
        ),
    ]
