# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0042_listadesubstantivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='testapalavra',
            name='numero',
            field=models.TextField(default=1, verbose_name='nnumero'),
            preserve_default=False,
        ),
    ]
