# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0043_testapalavra_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testapalavra',
            name='numero',
            field=models.IntegerField(verbose_name='nnumero'),
        ),
    ]
