# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-31 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0045_parametrosdeajuste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosselecaotemas',
            name='delta',
        ),
        migrations.RemoveField(
            model_name='dadosselecaotemas',
            name='f',
        ),
        migrations.RemoveField(
            model_name='dadosselecaotemas',
            name='fb',
        ),
    ]
