# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0046_auto_20170531_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospreproc',
            name='flag_resultados',
            field=models.TextField(default=1, verbose_name='resultado'),
            preserve_default=False,
        ),
    ]
