# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0048_dadospreproc_flag_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospreproc',
            name='flag_test',
            field=models.TextField(default=1, verbose_name='teste'),
            preserve_default=False,
        ),
    ]
