# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-15 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0049_dadospreproc_flag_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospreproc',
            name='flag_test',
        ),
    ]
