# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0050_remove_dadospreproc_flag_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospreproc',
            name='flag_resultados',
        ),
        migrations.AddField(
            model_name='parametrosdeajuste',
            name='acuidade',
            field=models.IntegerField(default=100, verbose_name='Freq_min_de_bigramas'),
        ),
        migrations.AlterField(
            model_name='dadospreproc',
            name='flag_completo',
            field=models.TextField(verbose_name='Flag - Exec. Completa'),
        ),
        migrations.AlterField(
            model_name='dadospreproc',
            name='flag_testapalavra',
            field=models.TextField(verbose_name='Flag -Testa Substantivo'),
        ),
    ]
