# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0052_parametrosdeajuste_num_tweets'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdeajuste',
            name='permitir_RT',
            field=models.CharField(default=100, max_length=10, verbose_name='RT'),
        ),
    ]
