# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0053_parametrosdeajuste_permitir_rt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrigePalavra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra_correta', models.TextField(verbose_name='palavra_correta')),
                ('palavra', models.TextField(verbose_name='palavra')),
            ],
        ),
    ]
