# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-22 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0054_corrigepalavra'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosselecaotemas',
            name='sel_betw',
            field=models.CharField(default='sim', max_length=10, verbose_name='Betwweeness?'),
        ),
        migrations.AddField(
            model_name='dadosselecaotemas',
            name='sel_clos',
            field=models.CharField(default='sim', max_length=10, verbose_name='Closeness?'),
        ),
        migrations.AddField(
            model_name='dadosselecaotemas',
            name='sel_graus',
            field=models.CharField(default='sim', max_length=10, verbose_name='Graus?'),
        ),
    ]
