# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-26 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0055_auto_20170622_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdeajuste',
            name='check_betw',
            field=models.CharField(default='sim', max_length=10, verbose_name='betweenness'),
        ),
        migrations.AddField(
            model_name='parametrosdeajuste',
            name='check_clos',
            field=models.CharField(default='sim', max_length=10, verbose_name='closeness'),
        ),
        migrations.AddField(
            model_name='parametrosdeajuste',
            name='check_grau',
            field=models.CharField(default='sim', max_length=10, verbose_name='graus'),
        ),
    ]
