# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0056_auto_20170626_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelaranking',
            name='closeness',
        ),
        migrations.RemoveField(
            model_name='tabelaranking',
            name='closeness_norm',
        ),
        migrations.AddField(
            model_name='tabelaranking',
            name='eigenvector',
            field=models.FloatField(default=1, verbose_name='eigenvector'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tabelaranking',
            name='eigenvector_norm',
            field=models.FloatField(default=1, verbose_name='eigenvector_norm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dadosselecaotemas',
            name='p_bet',
            field=models.FloatField(verbose_name='Peso eigenvector'),
        ),
        migrations.AlterField(
            model_name='dadosselecaotemas',
            name='sel_clos',
            field=models.CharField(default='sim', max_length=10, verbose_name='eigenvector?'),
        ),
        migrations.AlterField(
            model_name='parametrosdeajuste',
            name='check_clos',
            field=models.CharField(default='sim', max_length=10, verbose_name='eigenvector'),
        ),
        migrations.AlterField(
            model_name='pesosealpha',
            name='p_close',
            field=models.FloatField(verbose_name='Peso_eigenvector'),
        ),
    ]
