# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0057_auto_20180314_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosselecaotemas',
            old_name='p_clos',
            new_name='p_eigen',
        ),
        migrations.RenameField(
            model_name='dadosselecaotemas',
            old_name='sel_clos',
            new_name='sel_eigen',
        ),
        migrations.RenameField(
            model_name='parametrosdeajuste',
            old_name='check_clos',
            new_name='check_eigen',
        ),
        migrations.RenameField(
            model_name='pesosealpha',
            old_name='p_close',
            new_name='p_eigene',
        ),
    ]
