# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0058_auto_20180314_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdeajuste',
            name='faixa_histo',
            field=models.FloatField(default=0.2, verbose_name='Faixa'),
        ),
    ]
