# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0059_parametrosdeajuste_faixa_histo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdeajuste',
            name='exc_cluster',
            field=models.IntegerField(default=1, verbose_name='Exclusao_de_cluster'),
            preserve_default=False,
        ),
    ]
