# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0060_parametrosdeajuste_exc_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracaonew',
            name='tema',
        ),
        migrations.AddField(
            model_name='extracaonew',
            name='corte',
            field=models.FloatField(default=1, verbose_name='corte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extracaonew',
            name='irgs',
            field=models.FloatField(default=1, verbose_name='IRGS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extracaonew',
            name='irgs_p',
            field=models.FloatField(default=1, verbose_name='IRGS%'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extracaonew',
            name='irse',
            field=models.FloatField(default=1, verbose_name='IRSE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extracaonew',
            name='irse_p',
            field=models.FloatField(default=1, verbose_name='IRSE%'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extracaonew',
            name='peso',
            field=models.FloatField(default=1, verbose_name='peso'),
            preserve_default=False,
        ),
    ]
