# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0064_auto_20180413_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extracaonew',
            name='irgs_p',
        ),
        migrations.RemoveField(
            model_name='extracaonew',
            name='irse_p',
        ),
        migrations.AddField(
            model_name='extracaonew',
            name='rep_geral',
            field=models.TextField(default=1, verbose_name='Representatividade_geral'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extracaonew',
            name='rep_tema',
            field=models.TextField(default=1, verbose_name='Representativadade_tema'),
            preserve_default=False,
        ),
    ]
