# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0065_auto_20180413_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosextracaonew',
            name='quantidade',
        ),
    ]
