# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0067_auto_20180413_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdeajuste',
            name='nc',
            field=models.IntegerField(default=1, verbose_name='CLusters dos temas principais'),
        ),
    ]
