# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0068_parametrosdeajuste_nc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temas', models.TextField(verbose_name='Temas')),
                ('subtemas', models.TextField(verbose_name='Subtemas')),
            ],
        ),
    ]
