# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0069_subtemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clusters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nucleos', models.TextField(verbose_name='Nucleos')),
                ('subtemas', models.TextField(verbose_name='Subtemas')),
            ],
        ),
    ]
