# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0070_clusters'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusters',
            name='situacao',
            field=models.TextField(default=1, verbose_name='Situa\xe7\xe3o'),
            preserve_default=False,
        ),
    ]
