# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0072_auto_20180426_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusters',
            name='etapa',
            field=models.IntegerField(null=True, verbose_name='Etapa'),
        ),
    ]
