# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0074_auto_20180426_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temasnew',
            name='irt_p',
        ),
        migrations.AddField(
            model_name='temasnew',
            name='classificacao',
            field=models.TextField(default=1, verbose_name='Classificacao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temasnew',
            name='irt_l',
            field=models.FloatField(default=1, verbose_name='IRT Local (%)%'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temasnew',
            name='irt',
            field=models.FloatField(verbose_name='IRT Global (%)'),
        ),
    ]
