# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0076_auto_20180426_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temasnew',
            name='irt_l',
            field=models.FloatField(verbose_name='IRT Local (Sem refer\xeancia)'),
        ),
    ]
