# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0077_auto_20180426_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapasTemasESubtemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.TextField(verbose_name='Tema')),
                ('subtema', models.TextField(verbose_name='Subtema')),
                ('irt_l', models.FloatField(verbose_name='IRT (subtema) Local Refer\xeanciado')),
            ],
        ),
    ]
