# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0079_remove_clusters_q_nucleos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapastemasesubtemas',
            name='irt_l',
        ),
        migrations.AddField(
            model_name='mapastemasesubtemas',
            name='grau',
            field=models.FloatField(default=1, verbose_name='Grau local'),
            preserve_default=False,
        ),
    ]
