# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0080_auto_20180502_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapastemasesubtemas',
            name='irt_l',
            field=models.FloatField(default=1, verbose_name='IRT local'),
            preserve_default=False,
        ),
    ]
