# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0081_mapastemasesubtemas_irt_l'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temasnew',
            name='irt_l',
        ),
    ]
