# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0082_remove_temasnew_irt_l'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtemas',
        ),
        migrations.RemoveField(
            model_name='parametrosdeajuste',
            name='nc',
        ),
    ]
