# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0084_auto_20180502_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapastemasesubtemas',
            name='ident',
            field=models.TextField(default=1, verbose_name='Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clusters',
            name='caminho',
            field=models.TextField(verbose_name='Caminho'),
        ),
    ]
