# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0085_auto_20180502_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusters',
            name='fim_de_arvore',
            field=models.IntegerField(default=1, verbose_name='Cluster Final?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapastemasesubtemas',
            name='fim_de_arvore',
            field=models.IntegerField(default=1, verbose_name='Cluster Final?'),
            preserve_default=False,
        ),
    ]
