# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0086_auto_20180502_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clusters',
            name='fim_de_arvore',
            field=models.TextField(verbose_name='Cluster Final?'),
        ),
        migrations.AlterField(
            model_name='mapastemasesubtemas',
            name='fim_de_arvore',
            field=models.TextField(verbose_name='Cluster Final?'),
        ),
    ]
