# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0087_auto_20180502_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentencasAvaliadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.TextField(verbose_name='Tema')),
                ('subtema', models.TextField(verbose_name='SubTema')),
                ('proto', models.TextField(verbose_name='Proto Frase')),
                ('frase', models.TextField(verbose_name='Frase')),
                ('peso', models.FloatField(verbose_name='peso')),
                ('corte', models.FloatField(verbose_name='corte')),
                ('irse', models.FloatField(verbose_name='IRSE')),
            ],
        ),
        migrations.DeleteModel(
            name='ExtracaoNew',
        ),
    ]
