# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-05 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0089_sentencasextraidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencasextraidas',
            name='representatividade',
            field=models.TextField(default=1, verbose_name='Representatividade'),
            preserve_default=False,
        ),
    ]
