# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0090_sentencasextraidas_representatividade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosdeajuste',
            name='radio_r',
            field=models.TextField(default=0.0, verbose_name='Representatividade_minima'),
        ),
    ]
