# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0091_auto_20180506_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosdeajuste',
            name='check_betw',
        ),
        migrations.RemoveField(
            model_name='parametrosdeajuste',
            name='check_eigen',
        ),
        migrations.RemoveField(
            model_name='parametrosdeajuste',
            name='check_grau',
        ),
    ]
