# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0092_auto_20180506_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametrosdeajuste',
            name='acuidade',
        ),
    ]
