# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0093_remove_parametrosdeajuste_acuidade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosSelecaoTemas',
        ),
        migrations.DeleteModel(
            name='PesosEAlpha',
        ),
        migrations.RemoveField(
            model_name='dadospreproc',
            name='flag_completo',
        ),
        migrations.RemoveField(
            model_name='dadospreproc',
            name='flag_testapalavra',
        ),
    ]
