# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-06 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0094_auto_20180506_2034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadosExtracaoNew',
        ),
        migrations.DeleteModel(
            name='ProtoFrasesNew',
        ),
        migrations.RemoveField(
            model_name='parametrosdeajuste',
            name='dr_delta_min',
        ),
        migrations.AlterField(
            model_name='testapalavra',
            name='numero',
            field=models.IntegerField(verbose_name='numero'),
        ),
    ]
