# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0095_auto_20180506_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencasavaliadas',
            name='string_graus',
            field=models.TextField(default=1, verbose_name='Graus da Protofrase'),
            preserve_default=False,
        ),
    ]
