# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0096_sentencasavaliadas_string_graus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencasextraidas',
            name='proto',
            field=models.TextField(default=1, verbose_name='Proto Frase'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentencasextraidas',
            name='string_graus',
            field=models.TextField(default=1, verbose_name='Graus da Protofrase'),
            preserve_default=False,
        ),
    ]
