# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0097_auto_20180508_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentencasNucleos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.IntegerField(verbose_name='Ident')),
                ('proto', models.TextField(verbose_name='Proto Frase')),
                ('frase', models.TextField(verbose_name='Frase')),
                ('frase_l', models.TextField(verbose_name='Frase Lematizada')),
                ('peso', models.FloatField(verbose_name='peso')),
                ('string_graus', models.TextField(verbose_name='Graus da Protofrase')),
                ('nucleo', models.TextField(verbose_name='N\xfacleo da Frase')),
            ],
        ),
        migrations.AddField(
            model_name='sentencasextraidas',
            name='ident',
            field=models.IntegerField(default=1, verbose_name='Ident'),
            preserve_default=False,
        ),
    ]
