# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-10 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0098_auto_20180508_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentencasnucleos',
            name='frase_l',
        ),
        migrations.AddField(
            model_name='sentencasnucleos',
            name='representatividade',
            field=models.TextField(default=1, verbose_name='Representatividade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentencasnucleos',
            name='subtema',
            field=models.TextField(default=1, verbose_name='SubTema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentencasnucleos',
            name='tema',
            field=models.TextField(default=1, verbose_name='Tema'),
            preserve_default=False,
        ),
    ]
