# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0099_auto_20180510_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentencasnucleos',
            name='irse',
            field=models.FloatField(default=1, verbose_name='IRSE'),
            preserve_default=False,
        ),
    ]
