# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0100_sentencasnucleos_irse'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdeajuste',
            name='execucao',
            field=models.TextField(default='normal', verbose_name='Execucao'),
        ),
    ]
