# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0101_parametrosdeajuste_execucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrosdeajuste',
            name='corte_n',
            field=models.IntegerField(default=10, verbose_name='Corte Extra\xe7\xe3o dos N\xfacleos (%)'),
        ),
    ]
