# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0102_parametrosdeajuste_corte_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentencasGlobais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representatividade', models.TextField(verbose_name='Representatividade')),
                ('peso', models.FloatField(verbose_name='peso')),
                ('nucleo', models.TextField(verbose_name='N\xfacleo da Frase')),
                ('irseg', models.FloatField(verbose_name='IRSEG')),
            ],
        ),
    ]
