# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0103_sentencasglobais'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrasesGlobais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representatividade', models.TextField(verbose_name='Representatividade')),
                ('peso', models.FloatField(verbose_name='peso')),
                ('esquerda', models.TextField(verbose_name='Esquerda')),
                ('nucleo', models.TextField(verbose_name='N\xfacleo da Frase')),
                ('direita', models.TextField(verbose_name='Direita')),
            ],
        ),
    ]
