# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0104_frasesglobais'),
    ]

    operations = [
        migrations.AddField(
            model_name='frasesglobais',
            name='cor',
            field=models.TextField(default=1, verbose_name='Cor'),
            preserve_default=False,
        ),
    ]
