# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-22 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrator', '0105_frasesglobais_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='frasesglobais',
            name='size',
            field=models.TextField(default=1, verbose_name='Tamanho'),
            preserve_default=False,
        ),
    ]
